- ds-caselaw-ingester/lambda_function.py
We are still testing the main ingester code, errors thrown by the retry code
are swallowing other errors. Don't retry for now - renable this once we have
ingestion working.
> Temporarily remove call to `send_retry_message`

- .github/workflows/deploy-production.yml
For now, deploy everything on main, but we can change this to tags-only later. I've added the secrets to the build environment already.
> add job to deploy to production

- ds-caselaw-ingester/lambda_function.py
Rollbar: https://rollbar.com/dxw/tna-caselaw-ingester/items/23/
```
AttributeError: 'NoneType' object has no attribute 'replace' (Most recent call last)
File /var/task/lambda_function.py line 154 in handler args locals
uri = extract_uri(metadata)
File /var/task/lambda_function.py line 43 in extract_uri args locals
'return metadata["parameters"]["PARSER"]["uri"]....s://caselaw.nationalarchives.gov.uk/id/\', \'\')'
```
If the metadata JSON doesn't contain any reference to a uri, the lambda is
erroring without throwing a UriNotFoundException, because it can't perform a
`replace` on a non-existent object. Move the UriNotFoundException up into the
`extract_uri` method to catch this error.
> Throw a UriNotFoundException if the URI is not part of the message

- ds-caselaw-ingester/lambda_function.py
Other exceptions should be raised to Rollbar but not trigger retries
Trello: https://trello.com/c/eC7a2yUL/474-dont-retry-ingestions-that-have-a-missing-uri-or-other-fields-it-wont-help
> Only send a retry message if we cannot access the Tarball from s3

- docker-compose.yml
- ds-caselaw-ingester/lambda_function.py
- requirements/base.txt
If the consignment from TRE does not contain a URI, or only contains the stem of a URI, create a `failure` uri from the consignment reference. Use this uri to store a document in Marklogic, either the document XML (if it exists) or a dummy XML document with the parser log output in it if not.
All other documents in the tarball should be processed and stored as normal (if they exist).
> Create a `failure` URI and document in Marklogic if there is no URI in the consignment

- ds-caselaw-ingester/lambda_function.py
exception caught by Rollbar:
```
ReadError: file could not be opened successfully (Most recent call last)
File /var/task/lambda_function.py line 170 in handler args locals
tar = tarfile.open(filename, mode='r')
File /var/lang/lib/python3.9/tarfile.py line 1625 in open args locals
raise ReadError("file could not be opened successfully")
ReadError: file could not be opened successfully
```
When the tarball cannot be read, send a retry message to the queue.
> Send a retry message on tarfile.ReadError

- ds-caselaw-ingester/lambda_function.py
Situation:
1. We now don't retry on all errors
2. We throw an error if we've reached the max retry count
3. TRE complains if the retry counts don't match what it expects
This means that existing ingestions that failed and hit the retry limit can't be manually triggered any more. To fix this, I want to bump up our retry limit for a while, then put it back when we've processed everything that was stuck. I thought the best way would be to move it into the ENV. I've set this ENV var on both lambda environments already.
I thought the code was a little clearer the way I've written it and named things, sorry if it's awkward to parse in your brain to make sure it does the same thing!
> Make retry maximum configurable via ENV

- ds-caselaw-ingester/lambda_function.py
If a ReadError or ProtocolError is thrown, we want to retry ingesting the
file - we don't necessarily need to know this has happend in Rollbar. We only
need to raise errors in Rollbar if the maximum retries are exceeded, or if
another error is thrown.
This should reduce some of the noise in Rollbar for the ingester.
> Don't raise ReadError or ProtocolError to Rollbar

- ds-caselaw-ingester/lambda_function.py
Don't throw a KeyError if `parser.log` isn't in the tarball. This isn't a
fatal error, we can still ingest the file as a `failure`.
Rollbar: https://rollbar.com/dxw/tna-caselaw-ingester/items/30/
> Don't raise an error if parser.log not found

- .pre-commit-config.yaml
- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
- setup.cfg
Editors were receiving occasional notifications of a new judgment, but the
attached link to the editorial UI lead to a 404 page. On investigation,
it appears two judgments have generated this email but are not in Marklogic.
In order to track down why this might be happening, we have refactored the
judgment insertion/update flow. There is a possibility the call to
`api_client.insert_judgment_xml` was failing, but not exception was being
caught and the notification of a new judgment was being sent anyway.
This refactor should hopefully catch any errors with updating/inserting a
judgment and not allow a notification to be sent if either fails.
This refactor also adds some new tests.
Trello: https://trello.com/c/hfOotu2k
> Refactor editor notification flow for new/updated judgments

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
It looks like sometimes, the XML file name that's meant to be in the
metadata is not present. If this is the case, handle the exception and return
None, instead of raising an error.
Rollbar:
https://rollbar.com/dxw/tna-caselaw-ingester/items/39/?item_page=0&#traceback
> Add check to guard against an empty XML file name

- ds-caselaw-ingester/lambda_function.py
On 21/07/22 we had 5 failures from TRE. On inspection, we found a few "corner cases" where the ingester lambda was not handling errors cleanly:
1) If there is no parser.log present, we were expecting to catch a KeyError from `copy_file()`. But `copy_file()` throws a custom FileNotFoundException, and we were not catching it. As a result, none of the tarfile contents were being saved to S3, because the lambda bombed out before the files could be copied.
2) We expect to iterate over a list of images in the metadata file and store those images. But if there is no `images` entry in the metadata JSON, the lambda was again throwing an uncaught exception. Again, this was causing the tarfile contents to not be saved to S3.
3) As a side-effect of the above two, the lambda was also throwing an error …
> Debugging more corner cases in the ingester

- ds-caselaw-ingester/tests.py
https://trello.com/c/5GUPk9V7/1105-adjust-getconsignmentreference-in-ingester
We could already extract the consignment ref from a presigned URL, we just didn't have a test proving it!
> Add a test to prove that we can extract a consignment ref from a presigned url

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
Editors have requested that if a judgment is ingested and it is an update to an existing judgment, the judgment is unpublished. This is to prevent any unchecked judgments appearing on the Public UI. A judgment must be re-checked by the editors if it is an update.
https://trello.com/c/5IUSmnjQ
> If a judgment is updated, unpublish it

- Makefile
- README.md
- scripts/setup-localstack.sh
Improve the way we test a tarfile locally. You can now pass a test tarfile as a parameter to the `make` commands, instead of editing the files in `aws_examples` to point to a different test tarfile.
This has been partially pulled from https://github.com/nationalarchives/ds-caselaw-ingester/pull/45
> Improve testing mechanism

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
Slack discussion: https://dxw.slack.com/archives/C02TP2L2Z0F/p1671100904231339
After a deploy it was discovered that notification emails weren't being sent; the code that suppressed emails on staging had previously only been deployed to staging, and checked the `ROLLBAR_ENV` was set to `production`, rather than the value of `prod` that's actually used, so it also suppressed production emails once fully rolled out.
> Email notifications should trigger on correct spelling of ROLLBAR_ENV, 'prod'

- docker-compose.yml
Suppress the following error:
```
localstack_1  | ERROR
localstack_1  | ============================================================================
localstack_1  |   It seems you are mounting the LocalStack volume into /tmp/localstack.
localstack_1  |   This will break the LocalStack container! Please update your volume mount
localstack_1  |   destination to /var/lib/localstack.
localstack_1  |   You can suppress this error by setting LEGACY_DIRECTORIES=1.
localstack_1  |
localstack_1  |   See: https://github.com/localstack/localstack/issues/6398
localstack_1  | ============================================================================
localstack_1  |
ds-caselaw-ingester_localstack_1 exited with code 1
```
> Update docker configuration for localstack

- README.md
- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
Reverts https://github.com/nationalarchives/ds-caselaw-ingester/pull/64 as we're not ready for it and it blocks ingester deploy.
> Revert no-splat

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
https://trello.com/c/pAhbbMGO/1154-ingester-use-right-document-type-in-ingested-document-editor-emails
> Ingester notification email contains document type (Judgment/Press Summary)

- ds-caselaw-ingester/lambda_function.py
A small rearrangement of the saving stuff so that v2 messages copy the tar.gz file first, so it can be examined for debugging purposes.
> Save tarfile first to aid debugging

- ds-caselaw-ingester/lambda_function.py
I'd failed to realise that the previous PR didn't solve the problem because the error was a little earlier -- we now deliberately save the tar gz so we can take a look inside. We should remove this code when we're done.
> Debug: save file first

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
We search for `-metadata.json` to avoid the spurious `metadata.json`
> Avoid collisions with metadata.json when looking for TDR-2023-4DR-metajson.json

- requirements/base.txt
- Upgrade to apiclient 14.0.2 and added mypy-botp dependencies since it seems apiclient now depdends on them but they must be extras or something and so we need to install them here otherwise we error for example with:
```
ds-caselaw-ingester/lambda_function.py:15: in <module>
from caselawclient.Client import (
venv/lib/python3.11/site-packages/caselawclient/Client.py:18: in <module>
from caselawclient.models.documents import (
venv/lib/python3.11/site-packages/caselawclient/models/documents.py:13: in <module>
from .utilities.aws import (
venv/lib/python3.11/site-packages/caselawclient/models/utilities/aws.py:8: in <module>
from mypy_boto3_s3.client import S3Client
E   ModuleNotFoundError: No module named 'mypy_boto3_s3'
```
https://trello.com/c/p9LRm2Wi/1210-use-apiclient-13-save-versioni …
> Upgrade to apiclient 14.0.2

- .gitignore
- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
- requirements/base.txt
- scripts/test
Note: this changes how we handle environment variables; take care that this works correctly in staging before deploying to live.
> ⚠️ Set user agent and build own API client object

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
Also a light refactoring of the metadata extraction
We discovered that new judgments were being parsed twice if they didn't have a TDR section, since the sending of the email would fail since the metadata couldn't be extracted.
> Fix sending a new judgment notification if there's no TDR section

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
They are catch-all exceptions for unexpected behaviour -- it's OK to stop
and report the situation rather than plow on pretending everything's fine.
> Allow `MarklogicCommunicationError`s to crash ingester

- renovate.json
Our dependency files for pip are in a strange place which means they're not automatically found by Renovate. This fixes the problem by explicitly providing their locations.
> Tell Renovate where to find our dependency files

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
- requirements/base.txt
Use `autospec` to make sure the functions we're calling actually exist
Rename save_judgment_xml to update_document_xml
Add annotations
> Add annotations and rename functions to make v16 compatible

- .github/workflows/deploy-production.yml
- .github/workflows/deploy.yml
- template.yml
Previously we didn't define any environment variables at deploy time; instead we set them manually. A configuration change when we moved from Python 3.9 to 3.11 caused SAM to redefine the infrastructure, and this in turn caused a all existing environment variables to be wiped, bringing down the staging ingester.
This PR moves to defining the environment variables in the `template.yml` file which is used by SAM. The exact values are passed in at deploy time by GitHub Actions as part of configuring the infrastructure.
Variables are stored in GitHub environments.
> Define environment variables and timeout in code

- template.yml
The configuration should be within `Properties` so it's visible to CloudFormation, but instead of raising an error at this incorrect configuration SAM silently fails.
> Fix incorrect VPC config indentation

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
- requirements/base.txt
Using the new richer `VersionAnnotations` in v17 of the API client, populate them with richer information about what has happened up to the point of ingestion.
> Rich annotations for new versions

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
Discovered when Jim was putting something into S3 that the key that comes from the SNS of an S3 upload is escaped:
`\"key\":\"IAC1/2010+Reported/%5B2010%5D+UKAIT+00001-00003/00002_ukait_2010_ik_pakistan.tar.gz\"`
We need to unescape that to get the correct name of the key.
> S3 SNS keys are quote-plus escaped, unquote them.

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
`set_published()` defaults to False. We want it to be True.
See also https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/482 to disarm this footgun.
> Explicitly make sure we set_published(True), not the implicit False

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
Documents that are reparsed do not contain a docx file; a slight departure from previous expectations that every tar.gz file must have a docx file. It's possible that we could check whether we're expecting a tar.gz file based on the message type, but that feels like overcomplicating things.
> Support tar.gz that have no docx and have nilsy docx filename in the metadata

- ds-caselaw-ingester/lambda_function.py
There was a bug in the no_docx code -- we changed the local filename we tried to read from, not the remote filename in S3.
> Don't change the local filename, only the stored filename

- .gitignore
- .pre-commit-config.yaml
- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/test_sqid.py
- ds-caselaw-ingester/tests.py
- pyproject.toml
- setup.cfg
A series of commits which together make all of FCL's repositories behave more consistently with regard to tooling.
FCL-176
> [FCL-176] Tooling configuration audit

- docker-compose.yml
We were having issues with errors on pdf-converter where the v2 AWS API was trying to be used but was causing errors. Upgrading fixed them.
Something like:
localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs)
> Upgrade localstack to 3.5.0

- .github/workflows/deploy.yml
* The AWS OIDC (for the staging workflow) requires the `id-token` permission
> [FCL-447] Fix Staging workflow permissions

- .github/workflows/deploy-production.yml
* The production workflow creates a tag on the repository, which requires the `content: write` permission
> Chaneg Production workflow permissions

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
We updated the api client to use document.save_identifiers() not document.identifiers.save() -- implement that change here.
> Use save_identifiers on document not identifiers.save()

- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
- pyproject.toml
Switch on some more ruff checks and make necessary fixes to improve overall code quality, and prevent future errors creeping in.
> Enable more ruff checks to improve code quality

- template.yml
We accidentally changed `python3.11` to `python2` instead of `python3.12`.
> [FCL-674] Fix typo in deployed python version

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- ds-caselaw-ingester/lambda_function.py
- ds-caselaw-ingester/tests.py
- requirements/base.txt
Add several missing type annotations to the codebase, and make necessary adjustments where needed so that Python is being explicit about types rather than relying on implicit type conversions.
This gives us a more solid base for future refactoring work.
> [FCL-644] Improve typing and code robustness

- scripts/test
Add `__init__.py` to attempt to make lambda happy
The error was:
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': attempted relative import with no known parent package
Traceback (most recent call last):
There was no traceback.
> Add `__init__.py` to attempt to make lambda happy

- .pre-commit-config.yaml
- requirements/base.txt
- src/ds_caselaw_ingester/ingester.py
This is just a facade through to the function in the API Client, so that when we harmonise document creation in future there's less potential friction.
> [FCL-733] Add new property to identify ingested document type based on XML root node

- tests/conftest.py
- tests/tests.py
On trying to make changes to make the ingester use the v34 api changes, the tests would not run cleanly locally.
> Get local tests working with relative paths

- .pre-commit-config.yaml
- requirements/base.txt
- src/ds_caselaw_ingester/ingester.py
- tests/tests.py
API v34 adds a requirement that calls to `insert_document_xml` have a doctype; we add this by using the new document lookup.
> v34 compatibility doctype

- src/ds_caselaw_ingester/ingester.py
- tests/test_identifier_assignment.py
- tests/tests.py
Press Summaries on staging were getting judgment-style NCN identifiers. This should fix it (but could do with eyeballing on staging to check it's doing the right thing).
We didn't deploy the previous to production so we don't need to worry about identifier corruption on production.
> Fix press summaries not getting right identifier class in ingester

- src/ds_caselaw_ingester/ingester.py
- tests/test_fixtures.py
- tests/tests.py
To allow us to better sequence some deploys, temporarily switch the ingester to handing out old-style NCN-based URIs
> Reinstate handing out NCN-based URIs for the time-being

- src/ds_caselaw_ingester/ingester.py
We don't want to have to explicitly specify the correct NCN-based identifier for every possible document type; only do it for ones which we care about.
> Make identifier class lookup non-exhaustive

- src/ds_caselaw_ingester/ingester.py
- tests/tests.py
Use apiclient Document class methods to publish and unpublish documents in ingester in consistent manner to editor ui
> Use apiclient Document class methods to publish and unpublish documents in ingester in consistent manner to editor ui

- Makefile
- aws_examples/sns/parsed-judgment-v2.json
Attempting to run the ingester in localstack fails -- presumably we've made some changes but not kept the localstack config in sync.
Specifically, we're misinterpretting the names of the files inside the packages, where there's a mismatch in the filename vs. what the package itself identifies as.
> Fix localstack

- src/ds_caselaw_ingester/ingester.py
Ingester only knew about published identifiers, so attempting to ingest an document with a neutral citation matching an unpublished document wouldn't see it, and so would attempt to insert it which would fail as there was already an invisible document there.
> Ingester should know about unpublished identifiers

- .github/workflows/deploy-production.yml
Essentially the same as https://github.com/nationalarchives/ds-caselaw-editor-ui/pull/1999/files
It's why 1.15 deploy is broken.
Do a release afterwards
Not in Jira.
> Persist credentials so Endbug can use them

- docs/uri_logic.md
- src/ds_caselaw_ingester/ingester.py
- tests/tests.py
https://national-archives.atlassian.net/browse/FCL-673
Change the logic so that a document's URI is _always_ either an existing URI, or a new UUID-based one. We no longer mint new NCN-based URIs for any document, even if an NCN is present in the metadata.
⚠️ A significant change: once we deploy this, we will not be able to easily roll-back the PUI without exposing UUID based URIs.
> ⚠️ [FCL-673] Assign all new documents UUID-based URIs

- src/ds_caselaw_ingester/lambda_function.py
Whilst testing no-docx uploads, I discovered the logs do not contain the filename of the document, making it hard to search for Jim's uploads. We now output this.
https://national-archives.atlassian.net/issues/FCL-740
> Log the filename of the original tar.gz

- template.yml
https://dxw.slack.com/archives/C04UH0DHR2B/p1745508204194199
The SNS_TOPIC environment variable is blown away on deploy because it's a new lambda each time; this needs to be set up by Terraform.
https://national-archives.atlassian.net/jira/software/projects/FCL/boards/136?selectedIssue=FCL-825
> SNS_TOPIC environment variable populated from terraform

- src/ds_caselaw_ingester/ingester.py
- tests/tests.py
Fix the ingester's broken handling of performing a document revision, as opposed to insertion of a new document.
This case manifested itself where:
- A revision of an existing document had been submitted
- The parser had identified an NCN and was providing a URI hint in the metadata
- The existing document in MarkLogic had _not_ had its NCN corrected by an editor
In this case we would correctly resolve an existing document with the same slug as the hinted URI, but instead of setting the insertion URI to be that of the existing document we would set it to be the hinted URI. This would in turn cause a document not found exception, unless an editor had previously corrected the document's URI during the time period when the EUI would move a document on an NCN change.
FCL-851
> [FCL-851] Fix handling of document revision path

- .github/workflows/deploy-production.yml
- .github/workflows/deploy.yml
This variable is already present in GitHub Actions, but we weren't passing it into `sam deploy` so in turn it couldn't be included in the lambda deployments.
FCL-825
> [FCL-825] Add missing SnsTopic parameter to sam deploy

- template.yml
Specified Ingester Lambda MemorySize of 256MB in cloudformation config
https://national-archives.atlassian.net/browse/FCL-895
> Specify Ingester Lambda MemorySize of 256MB

- pyproject.toml
Allow most bandit checks.
Specifically turn off checks for [S108](https://docs.astral.sh/ruff/rules/hardcoded-temp-file/) for now
> The use of hardcoded paths for temporary files can be insecure. If an attacker discovers the location of a hardcoded path, they can replace the contents of the file or directory with a malicious payload. 
> Other programs may also read or write contents to these hardcoded paths, causing unexpected behavior.
Also turned on "G", which warns about dodgy logging formats.
https://my.slack.com/archives/C04FQ3GFGUQ/p1752504806313179?thread_ts=1752500939.154289&cid=C04FQ3GFGUQ
> [FCL-1050] Bandit, but suppress warnings about tmp/filename.tar.gz

- scripts/setup-localstack.sh
When deploying to real AWS, we upload to S3 and then create the lambda, which has a 250 meg limit; we move towards that model when running locally, so that we're not impeded by the 50 meg limit (we're at about 60.)
https://stackoverflow.com/questions/64875438
It's still broken, but not in this way.
> Upload lambda to localstack s3 first to avoid 50 meg filesize limit
