ds-caselaw-ingester/lambda_function.py

In production (when the lambda is running on AWS) we should not pass the
AWS credential type arguments. Not passing them forces the lambda to operate
under the assumed role, and passing them means the role definition is not
correct.
Locally, when these params are set, we need to pass them explicitly.

Do not pass `AWS_` credentials to boto AWS functions if they are not set

---

ds-caselaw-ingester/lambda_function.py

Raise exceptions if the XML file or URI are not found, triggering the retry message

Raise exceptions if the XML file or URI are not found

---

ds-caselaw-ingester/lambda_function.py
notify_templates/email/updated_judgment.md

Add separate email template for updated judgments

---

ds-caselaw-ingester/lambda_function.py

When changing the assert into an if, I didn't switch the sign of the comparison, so everything fails. :(
I've also put a limit on the length of the exception text.

Invert error check

---

Makefile
README.md
aws_examples/sns/parsed-judgment-v2.json
ds-caselaw-ingester/lambda_function.py
ds-caselaw-ingester/tests.py

Minimal changes to the ingester to support v1 and v2 at the same time.
Does not feature retry logic yet.

Ingest from TRE v2

---

README.md
ds-caselaw-ingester/lambda_function.py
ds-caselaw-ingester/tests.py

Possibly worth a discussion about the shape of collision URLs -- should we just use UUIDs?

If there's a collision, change name of URL

---

ds-caselaw-ingester/lambda_function.py
ds-caselaw-ingester/tests.py

Rearrange the code to bring the v1/v2 distinction together.

Refactor v1/v2 messages into classes

---

.github/workflows/codeql.yml
.pre-commit-config.yaml
README.md
aws_examples/s3/te-editorial-out-int/TRE-TDR-2022-DNWR-metadata.json
ds-caselaw-ingester/lambda_function.py
notify_templates/email/new_judgment.md
notify_templates/email/updated_judgment.md

These provide type checking (making sure we're only passing around what we expect), and keeping our non-code files looking nice and clean.

Add mypy and prettier to pre-commit

---

ds-caselaw-ingester/lambda_function.py
ds-caselaw-ingester/tests.py

* actually set it to be published on Marklogic
* don't send emails

Fix auto-publishing

---

ds-caselaw-ingester/lambda_function.py
ds-caselaw-ingester/tests.py

The ingester tests were silently "failures" -- they weren't finding the XML documents, because of mocks. Use actual tar-gz files instead. 
This uncovered some issues with how we handle the identifiers -- the v2 targz contains a different consignment ref (TRE-TDR-2000-123) to the folder name and v2 message (TDR-2000-123)

Use actual data for ingester tests

---

ds-caselaw-ingester/content_sqid.py
ds-caselaw-ingester/test_sqid.py
requirements/base.txt

Prototype for understanding how to use SQIDs.
TODO:

Prototype SQIDs in line with ADR 0018

---

.env.example
ds-caselaw-ingester/lambda_function.py
ds-caselaw-ingester/tests.py

JIRA: https://national-archives.atlassian.net/browse/FCL-85

Notify refactor

---

.pre-commit-config.yaml

Precommit autoupdate

---

.github/workflows/deploy-production.yml
.github/workflows/deploy.yml

* The OpenID Connector for authenticating with AWS rather than using credentials

[FCL-447] Change GitHub workflow to use AWS OIDC

---

.github/workflows/deploy-production.yml
.github/workflows/deploy.yml

* Staging and production have different roles to assume

[FCL-447] Fix workflow OIDC secret names

---

ds-caselaw-ingester/lambda_function.py

no doc on save_identifiers

---

ds-caselaw-ingester/lambda_function.py
requirements/base.txt

This is set up, but never actually used.

[FCL-717] Remove SQS Client from runtime code

---

requirements/base.txt
src/ds_caselaw_ingester/ingester.py
tests/conftest.py
tests/helpers.py
tests/test_identifier_assignment.py
tests/tests.py

Make use of the ParserLog document class for ingesting error documents

---

requirements/base.txt

Bump the API client to avoid issues with AWS keys. Hopefully this'll fix staging.

bump API client to 34.1.2

---

Makefile
src/ds_caselaw_ingester/ingester.py
tests/conftest.py
tests/test_fixtures.py
tests/test_ingester_methods.py
tests/tests.py

[FCL-732] identify existing documents at ingest

---

docs/uri_logic.md
src/ds_caselaw_ingester/ingester.py

Update our documentation so it's clearer what the ingester is actually trying to do.

Improve ingester documentation

---

docs/uri_logic.md
docs/workflow.md
src/ds_caselaw_ingester/ingester.py
tests/conftest.py
tests/tests.py

Update the behaviour of the ingester code to properly implement the logic described in the docs.

[FCL-791] Refactor decision logic around finding an existing document (where one exists)
